### PR TITLE
June 2020 test-fix

### PR DESCRIPTION
**Pull request by kylebunting**
The June 2020 test-fix is ready for review and QC.

Includes fixes for issue #34.

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hey Kyle!  Can you please check line 1770 of the step by step for me?  The instructions say enter Order # but the screenshot looks like it's Order *.  Not sure what's correct.
image

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hello!  Can you check line 240 in the student guide and 366 in the trainer guide for me?  It says Visual Studio (VS) cCode for OSS.  I've never seen cCode before...is it correct?
image

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, I fixed both of the issues you listed above.

**Comment by kylebunting** [comment]
Also, @DawnmarieDesJardins, note this pull request includes the dependency updates mentioned in issue #34 and pull requests #33 and #38.

**Pull request merged**
